### ISSUE TITLE
Bug: Nach abspielen => neuer Track hinzugefügt (ähnlich Bug #17)

### ISSUE THREAD

**Issue by pstadler1990** [pstadler1990/Drum#20]
java.lang.NullPointerException: src == null
                      at java.lang.System.arraycopy(Native Method)
                      at de.pstadler.drum.Sound.Playback.PlaybackConverter.convertPlaybackArrayListToPlaybackArrayForEachTrack(PlaybackConverter.java:48)

**Comment by pstadler1990** [comment]
Tritt auf, wenn ein Track keinen Sound hat = null;
